#Import zoomcamp model
FROM agrigorev/zoomcamp-model:2025

# First install the python 3.13.5, the slim version uses less space
# FROM python:3.13.5-slim-bookworm

# Install pipenv library in Docker 
#RUN pip install pipenv

# create a directory in Docker named app and we're using it as work directory 
#WORKDIR /app                                                                

#COPY requirements.txt .

# Copy the Pip files into our working directory 
#COPY ["Pipfile", "Pipfile.lock", "./"]

# install the pipenv dependencies for the project and deploy them.
#RUN pipenv install --deploy --system
#RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir uvicorn pydantic fastapi scikit-learn  # <-- Add this line

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV PATH="/app/.venv/bin:$PATH"

COPY "pyproject.toml" "uv.lock" ".python-version" ./
RUN uv sync --locked

COPY "predict.py" "pipeline_v1.bin" ./

EXPOSE 9696

ENTRYPOINT ["uvicorn", "predict:app", "--host", "0.0.0.0", "--port", "9696"]